name: app_assistente_vocal
description: Assistente visual com detecção de objetos para acessibilidade
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.5+5
  flutter_vision: ^1.1.4
  flutter_tts: ^3.8.5
  vibration: ^1.8.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/best_float32.tflite
    - assets/labels.txt
