# Pega o caminho do Flutter direto do servidor do Codemagic
flutter_root = ENV['FLUTTER_ROOT'] || File.join('..', '..', 'flutter')

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper.rb'), flutter_root)

platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_test_with_dev_pods = false

  # Instala as bibliotecas de Câmera, IA e Voz
  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Resolve conflitos de versão do iPhone
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end